services:
  db:
    image: pgvector/pgvector:pg16
    container_name: face_db
    environment:
      POSTGRES_USER: genius
      POSTGRES_PASSWORD: tensai102do
      POSTGRES_DB: tsukishima_face_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - face_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d facedb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: face_web
    volumes:
      - ./app:/app
      - deepface_models:/root/.deepface/weights
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://genius:tensai102do@db:5432/tsukishima_face_db
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - face_network
    restart: unless-stopped

volumes:
  pgdata:
  deepface_models:

networks:
  face_network:
    driver: bridge